"""create subscriptions table

迁移 ID: c3d021cf7115
父迁移: 
创建时间: 2026-01-30 07:44:01.271309

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c3d021cf7115'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_ba_tools',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_ba_tools_students',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nicknames', sa.JSON(), nullable=False),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.Column('avatars', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_ba_tools_students')),
    info={'bind_key': 'nonebot_plugin_ba_tools'}
    )
    op.create_table('nonebot_plugin_ba_tools_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('notification_type', sa.Enum('BIRTHDAY', 'BATTLE', name='subscriptionnotificationtype'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nonebot_plugin_ba_tools_subscriptions')),
    info={'bind_key': 'nonebot_plugin_ba_tools'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_ba_tools_subscriptions')
    op.drop_table('nonebot_plugin_ba_tools_students')
    # ### end Alembic commands ###
