"""update students table

迁移 ID: c68f2fcd5d59
父迁移: c3d021cf7115
创建时间: 2026-01-31 13:40:55.462200

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c68f2fcd5d59'
down_revision: str | Sequence[str] | None = 'c3d021cf7115'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_ba_tools_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('club', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('star_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('squad_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tactic_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bullet_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('armor_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weapon_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('character_age', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birthday_str', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('character_voice', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('illustrator', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hobby', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_introduction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('street_adaptation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outdoor_adaptation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('indoor_adaptation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nonebot_plugin_ba_tools_students', schema=None) as batch_op:
        batch_op.drop_column('indoor_adaptation')
        batch_op.drop_column('outdoor_adaptation')
        batch_op.drop_column('street_adaptation')
        batch_op.drop_column('profile_introduction')
        batch_op.drop_column('hobby')
        batch_op.drop_column('illustrator')
        batch_op.drop_column('character_voice')
        batch_op.drop_column('birthday_str')
        batch_op.drop_column('height')
        batch_op.drop_column('character_age')
        batch_op.drop_column('weapon_type')
        batch_op.drop_column('armor_type')
        batch_op.drop_column('bullet_type')
        batch_op.drop_column('position')
        batch_op.drop_column('tactic_role')
        batch_op.drop_column('squad_type')
        batch_op.drop_column('star_grade')
        batch_op.drop_column('club')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
